### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by andreasotto** [alialamshahi/SilverStripe-Tino#11]
I just tried to install on fresh silverstripe installation.
Your theme is showing up, but i don't see how to use the template HomePage for example.
The home page ist still with the regular Page template. There is no HomePage showing up somewhere.
Do you have some installation hints for me, please. Thank you very much.

**Comment by alialamshahi** [comment]
Hello,
In your Admin, click on page "Home", go to the "Settings", from Page Type please choose "HomePage"

**Comment by andreasotto** [comment]
In the Settings Tab there is no "HomePage" (just the other items like Page, which have been there before)

**Comment by andreasotto** [comment]
Update to answer this question to anyone who runs into the same problem:

You explicitly have to run /dev/build?flush=1 to create the database tables for the new template file 'HomePage.ss'. It is _not_ enough to just call ?flush=1 on any url (like stated in the documentation).

This detail seems not to be documented (or i overlooked it). 
I created a pull request with updated README.md and fixed small bugs in Layout/HomePage.ss. Hopefully this works now for everyone.

**Comment by alialamshahi** [comment]
Thanks, yes, you need to run /dev/build after you change things in mysite/code folder. thats because this template adds some functions to the page.
